### PR TITLE
Add Maven module "iride-entities" for IRIDE entity classes (issue #190)

### PR DESCRIPTION
**Pull request by seancrow**
#190 

- Added Maven module "iride-entities" for IRIDE entity classes
 - the module is empty at the present moment (nevertheless Maven compiles), sources will be added

### CODE REVIEW

**Comment by mbarto** [comment]
Instead of adding "HACK" files for committing the folders, I would wait for some file to be in the folders before committing this. I don't see value in adding an empty module.
Add the missing classes / resources / tests with another commit and then we will merge.

**Comment by seancrow** [comment]
Hi @mbarto 

Ok, I will add the missing sources/resources and then proceed with another commit with this PR

**Comment by seancrow** [comment]
Hi @mbarto, I'va added all the relevant sources and tests

**Comment by seancrow** [comment]
@mbarto for the time being the inclusion of this module in its parent one is commented, because I still have to remove the classes related to iride-entities from their original module, sec-iride.

**Pull request merged**
