### PR TITLE
Added config for unit tests

### LINKED ISSUE #3: Introduce unit tests
Create unit tests infrastructure and configuration

### PR DESCRIPTION
**Pull request by ridethepenguin**
* Added Karma configuration for single-run and continuous integration.
* Implemented simple unit test to prove infrastructure is working

Fixes #3

### CODE REVIEW

**Comment by mbarto** [comment]
Can you try to configure travis.yml so that tests are run byTravis CI?
You will then need to link the repo to Travis CI.

**Comment by ridethepenguin** [comment]
Yes, I meant to do it in a separate PR, as there's a separate issue for it (i.e. #4 ). Should I go ahead and add it in this PR?

**Comment by mbarto** [comment]
yes, please

**Comment by ridethepenguin** [comment]
Done, and the build is green! ;-)

**Pull request merged**
