### PR TITLE
IRIDE plugin configuration objects review (issue #184)

### PR DESCRIPTION
**Pull request by seancrow**
#184

### CODE REVIEW

**Comment by seancrow** [comment]
- IRIDE plugin configuration clsses refactored to add specialization ending with one config definition for the three security services customized in IRIDE context
  - AuthenticationProvider
  - RoleService
  - UserGroupService

**Comment by seancrow** [comment]
Hi @mbarto! I have a question regarding one of the configuration classes introduced with this PR, namely the `IrideRoleServiceConfig` one: at present it implements both the `SecurityRoleServiceConfig` interface, which defines configuration specific for `GeoServerRoleService`s, and the `SecurityAuthProviderConfig` interface, which is specific for `GeoServerAuthenticationProvider`.

I wonder if the latter interface implementation should be removed from `IrideRoleServiceConfig` definition, since an `IRIDE`-specialized authentication provider is going to be added with the next PR, and it will rely on its specific configuration class, `IrideAuthenticationProviderConfig`, which obviously implements `SecurityAuthProviderConfig`.

**Comment by mbarto** [comment]
SecurityAuthProviderConfig defines methods for getting / setting a usergroupservice, so I would say it's needed if your RoleService links a usergroupservice.

**Comment by seancrow** [comment]
Hi @mbarto, regarding your answer, what do you mean with a `RoleService` linking a `UserGroupService`?
In the  context of `IRIDE` integration, the `UserGroupService` is used by the specialized `AuthenticationProvider`, while, as far as I know, the `RoleService` should not need it.
But I'm not sure about this point.

**Comment by mbarto** [comment]
I don't know the details of the current Iride RoleService: if it doesn't use a UserGroupService, than the interface is not needed.

**Comment by seancrow** [comment]
Ok, I will double-check the current "incarnation" of `IRIDE` `RoleService`, probably it doesn't need any longer to implement `SecurityAuthProviderConfig`.

Thanks a lot @mbarto !

**Pull request merged**
