### PR TITLE
Local Maven repository directory for iridev2 dependency

### PR DESCRIPTION
**Pull request by seancrow**
- added a local Maven repository for unmanaged iridev2 dependency libraries
 - iridev2-pep-base-wsnmsf
 - iridev2-pep-helper-wsnmsf

### CODE REVIEW

**Comment by seancrow** [comment]
These are dependencies needed to let the various security services defined in sec-iride to query IRIDE service, and have been made available as Maven dependencies in a local project Maven repository.

**Comment by simboss** [comment]
We can publish them in the GeoSolutions Maven repository.

Git is not the place to go for JAR files :)

**Comment by seancrow** [comment]
OK, that's better! 

Therefore I'm going to close this PR, and I will send you those two jars to be published in GeoSolutions Maven repository, without having to add any local repository.

**Comment by simboss** [comment]
Ping mauro about this tomorrow.

He will help you out with the procedure to publish [here](http://maven.geo-solutions.it/).

**Comment by seancrow** [comment]
Perfect! Thanx a lot @simboss ! :)

**Pull request closed without merging**
