### PR TITLE
IRIDE SOAP response handling

### PR DESCRIPTION
**Pull request by seancrow**
- refactored pre-existing IRIDE entities and introduced a new entity to model IRIDE InfoPersona
 - those used by the plugin are now immutable
 - corrected IrideIdentity.toInternalRepresentation & IrideIdentity.toString algorithms
  - and JUnit unit tests
- introduced IRIDE "policies" registry and manager to incapsulate operations regarding calling IRIDE "policies"
 - introduced XSLTs to parse the various IRIDE "policies" responses
  - as well as specialized classes to handle XML transformations and error handling
  - and JUnit tests
 - introduced IRIDE entities XStream converters
  - and JUnit unit tests
  - used in tandem with XSLTs to produce IRIDE entities from the tansformed XMLs
- updated Maven POM
 - minor corrections
 - added Javadoc and Cobertura support
- more JUnit tests for IRIDE request FreeMarker templates

### CODE REVIEW

**Comment by seancrow** [comment]
@mbarto I have temporarily removed the test unit on IrideRoleService, because I had to refactor the underlying communication mechanism with IRIDE service to such an extent, to have the "building blocks" neededby the other Service, the UserGroup one, that the preexisting unit test was no longer aligned.
I'm going to put back in place that unit test as soon as I will have completed the development of the UserGroup service,  along with the necessary test on it.

**Comment by mbarto** [comment]
@seancrow Would it be possible (also for the future) to split up the work in smaller chunks so that we can ease the code review process?
I am not too happy of the unit tests removal. Could you for example, take out the IrideRoleService (and related tests) work out of this PR?

**Comment by seancrow** [comment]
Hi @mbarto. Ok for splitting up in smaller chunks the work done with the code: this has been an exception.
Regarding the unit test removal, I try to follow what you suggest: taking out, in the context of this PR only, the IridideRoleService class (as well as its references) to add it back again, with related unit test(s), in the next PR.

**Comment by seancrow** [comment]
@mbarto done with the temporary removal of IrideRoleService (and its references)

**Pull request merged**
